[project]
name = "test_tu"
authors = [
    { name = "HKuz", email = "heather.kusmierz@gmail.com"}
]
description = "Dummy ERPNext app to test Test Utils functionality"
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["version"]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.poetry]
version = "0.0.1"

[tool.poetry.dependencies]
python = ">=3.10,<3.15"
test_utils = {git = "https://github.com/hkuz/test_utils.git"}

[tool.poetry.group.tests.dependencies]
pytest = "^9.0.2"

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.2.0"
